
# Seleccionamos el aplicativo que queremos desplegar
global:
  serviceSelector:
    minio: true
    mysql: false
    mongo: false

# Valores para el cronjob de backup de minio
minio:
  endpoint: http://minio.minio:9000
  user: "defaultUser"
  password: "defaultPassword"
  serviceName: miniodump
  imageTag: 1.0.11
  reqMemory: 256Mi
  reqCpu: 200m
  pvcBackupName: backup
  cronTime: "0 3 * * *"
  pathBackup: /miniodump
  pathCompress: s3minio
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de mysql
mysql:
  serviceName: mysqldump
  imageTag: "1.0.0"
  reqMemory: 100Mi
  reqCpu: 100m
  pvcBackupName: backups
  cronTime: "*/5 * * * *"
  allDatabases: false
  backupDatabases: "basededatos1 basededatos2 sampledb"
  backupStorage: "exampleapp1"
  dbHost: "mysql"
  dbUser: "root"
  dbPass: "xxxxxxxxxxx"
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de mongo
mongo:
  serviceName: mongodump
  imageTag: "1.0.0"
  reqMemory: 100Mi
  reqCpu: 100m
  pvcBackupName: backups
  cronTime: "*/5 * * * *"
  allDatabases: false
  backupDatabases: "basededatos1 basededatos2 sampledb"
  backupStorage: "exampleapp1"
  dbHost: "mongodb"
  dbUser: "admin"
  dbPass: "xxxxxxxxxxx"
  deleteOldBackups: false
  maxBackupDays: 7