# Seleccionamos el servicio que queremos desplegar
global:
  serviceSelector:
    testing: true
    minio: false
    mysql: false
    pgsql: false
    mongo: false
    redis: false
    rsync: false
  registry: "docker.io"  
  image: "arpovea/arpovea-tools"
  imageTag: "1.0"

# Permite habilitar la opción para crear un buildConfig junto a su imageStream para entornos OpenShift
openshift:
  createBuildConfig: false

  imageStream:
    name: "arpovea-tools"

  buildConfig:
    outputImageStreamTag: "arpovea-tools:latest"
    sourceGitUri: "https://github.com/arpovea/arpovea-tools.git"
    sourceGitRef: "main"
    sourceContextDir: "docker"
    dockerfilePath: "Dockerfile"

# Valores para el deployment de testing:
testing:
  serviceName: "testing-service"
  replicas: 1
  image:
    pullPolicy: "IfNotPresent"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

# Valores para el cronjob de backup de minio
minio:
  serviceName: "miniodump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  endpoint: "http://minio.minio:9000"
  existingSecret: ""
  user: "dummyuser"
  password: "dummypass"
  pvcBackupName: "backups"
  cronTime: "0 3 * * *"
  pathBackup: "/miniodump"
  pathCompress: "s3minio"
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de mysql
mysql:
  serviceName: "mysqldump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  pvcBackupName: "backups"
  cronTime: "*/5 * * * *"
  allDatabases: false
  backupDatabases: "basededatos1 basededatos2 sampledb"
  backupStorage: "exampleapp1"
  existingSecret: ""
  dbHost: "mysql"
  dbUser: "dummyuser"
  dbPass: "dummypass"
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de mongo
mongo:
  serviceName: "mongodump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  pvcBackupName: "backups"
  cronTime: "*/5 * * * *"
  allDatabases: false
  backupDatabases: "basededatos1 basededatos2 sampledb"
  backupStorage: "exampleapp1"
  existingSecret: ""
  dbHost: "mongodb"
  dbUser: "dummyuser"
  dbPass: "dummypass"
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de pgsql
pgsql:
  serviceName: "pgdump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  pvcBackupName: "backups"
  cronTime: "*/5 * * * *"
  backupDatabases: "basededatos1 basededatos2 sampledb"
  backupStorage: "exampleapp1"
  existingSecret: ""
  dbHost: "postgresql"
  dbUser: "dummyuser"
  dbPass: "dummypass"
  deleteOldBackups: false
  maxBackupDays: 7

# Valores para el cronjob de backup de redis
redis:
  serviceName: "redisdump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  pvcBackupName: "backups"
  cronTime: "*/5 * * * *"
  backupStorage: "exampleapp"
  existingSecret: ""
  dbHost: "redis"
  dbUser: "dummyuser"
  dbPass: "dummypass"
  dbPort: 6379
  waitSaveRdb: 30
  deleteOldBackups: true
  maxBackupDays: 7

# Valores para el cronjob de backup de rsync
rsync:
  serviceName: "rsyncdump"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"
  pvcBackupName: "backups"
  pvcOriginName: "pvc-origin"
  cronTime: "*/5 * * * *"
  backupStorage: "exampleapp1"
  deleteOldBackups: false
  maxBackupDays: 7
