{{- if .Values.createBuildConfig }}
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.imageStream.name }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{ .Values.buildConfig.sourceGitUri }}
      ref: {{ .Values.buildConfig.sourceGitRef }}
    contextDir: {{ .Values.buildConfig.sourceContextDir }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: {{ .Values.buildConfig.dockerfilePath }}
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.buildConfig.outputImageStreamTag }}
{{- end }}
