{{- if .Values.global.serviceSelector.minio }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-{{ .Values.minio.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.minio.serviceName }}
spec:
  schedule: {{ .Values.minio.cronTime }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: miniodump
            image: '{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.imageTag }}'
            imagePullPolicy: Always
            command:
            - /bin/entrypoint_minio_dump.sh
            resources:
              requests:
                cpu: {{ .Values.minio.resources.requests.cpu }}
                memory: {{ .Values.minio.resources.requests.memory }}
              limits:
                cpu: {{ .Values.minio.resources.limits.cpu }}
                memory: {{ .Values.minio.resources.limits.memory }}
            envFrom:
            - configMapRef:
                name: cronjob-cm-{{ .Values.minio.serviceName }}
            - secretRef:
                name: {{ if .Values.minio.existingSecret }}{{ .Values.minio.existingSecret }}{{ else }}cronjob-secret-{{ .Values.minio.serviceName }}{{ end }}
            volumeMounts:
            - name: miniodump
              mountPath: {{ .Values.minio.pathBackup }}
          restartPolicy: Never
          volumes:
          - name: miniodump
            persistentVolumeClaim:
              claimName: {{ .Values.minio.pvcBackupName }}
{{- end }}
