{{- if .Values.global.serviceSelector.pgsql }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-{{ .Values.pgsql.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.pgsql.serviceName }}
spec:
  schedule: {{ .Values.pgsql.cronTime | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pgdump
            image: '{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.imageTag }}'
            imagePullPolicy: Always
            command: ["/bin/entrypoint_postgresql_dump.sh"]
            resources:
              requests:
                cpu: {{ .Values.pgsql.reqCpu }}
                memory: {{ .Values.pgsql.reqMemory }}
            envFrom:
            - configMapRef:
                name: cronjob-cm-{{ .Values.pgsql.serviceName }}
            - secretRef:
                name: {{ if .Values.pgsql.existingSecret }}{{ .Values.pgsql.existingSecret }}{{ else }}cronjob-secret-{{ .Values.pgsql.serviceName }}{{ end }}
            volumeMounts:
            - name: pgdump
              mountPath: /pgdump
          volumes:
          - name: pgdump
            persistentVolumeClaim:
              claimName: {{ .Values.pgsql.pvcBackupName }}
          restartPolicy: Never
{{- end }}
