{{- if .Values.global.serviceSelector.redis }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-{{ .Values.redis.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.redis.serviceName }}
spec:
  schedule: {{ .Values.redis.cronTime | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: redisdump
            image: '{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.imageTag }}'
            imagePullPolicy: Always
            command: ["/bin/entrypoint_redis_dump.sh"]
            resources:
              requests:
                cpu: {{ .Values.redis.resources.requests.cpu }}
                memory: {{ .Values.redis.resources.requests.memory }}
              limits:
                cpu: {{ .Values.redis.resources.limits.cpu }}
                memory: {{ .Values.redis.resources.limits.memory }}
            envFrom:
            - configMapRef:
                name: cronjob-cm-{{ .Values.redis.serviceName }}
            - secretRef:
                name: {{ if .Values.redis.existingSecret }}{{ .Values.redis.existingSecret }}{{ else }}cronjob-secret-{{ .Values.redis.serviceName }}{{ end }}
            volumeMounts:
            - name: redisdump
              mountPath: /redisdump
          volumes:
          - name: redisdump
            persistentVolumeClaim:
              claimName: {{ .Values.redis.pvcBackupName }}
          restartPolicy: Never
{{- end }}
