{{- if .Values.global.serviceSelector.rsync }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-{{ .Values.rsync.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.rsync.serviceName }}
spec:
  schedule: {{ .Values.rsync.cronTime | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rsyncdump
            image: '{{ .Values.global.registry }}/{{ .Values.global.image }}:{{ .Values.global.imageTag }}'
            imagePullPolicy: Always
            command: ["/bin/entrypoint_rsync_dump.sh"]
            resources:
              requests:
                cpu: {{ .Values.rsync.resources.requests.cpu }}
                memory: {{ .Values.rsync.resources.requests.memory }}
              limits:
                cpu: {{ .Values.rsync.resources.limits.cpu }}
                memory: {{ .Values.rsync.resources.limits.memory }}
            envFrom:
            - configMapRef:
                name: cronjob-cm-{{ .Values.rsync.serviceName }}
            volumeMounts:
            - name: rsyncdump
              mountPath: /rsyncdump
            - name: rsyncori
              mountPath: /rsyncori
              readOnly: true
          volumes:
          - name: rsyncdump
            persistentVolumeClaim:
              claimName: {{ .Values.rsync.pvcBackupName }}
          - name: rsyncori
            persistentVolumeClaim:
              claimName: {{ .Values.rsync.pvcOriginName }}
          restartPolicy: Never
{{- end }}
