{{- if .Values.global.serviceSelector.mysql }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm-{{ .Values.mysql.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.mysql.serviceName }}
data:
  ALL_DATABASES: {{ .Values.mysql.allDatabases | quote }}
  BACKUP_DATABASES: {{ .Values.mysql.backupDatabases | quote }}
  BACKUP_STORAGE: {{ .Values.mysql.backupStorage | quote }}
  DB_HOST: {{ .Values.mysql.dbHost | quote }}
  DELETE_OLD_BACKUPS: {{ .Values.mysql.deleteOldBackups | quote }}
  MAX_BACKUP_DAYS: {{ .Values.mysql.maxBackupDays | quote }}
{{- end }}
