{{- if .Values.global.serviceSelector.minio }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm-{{ .Values.minio.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.minio.serviceName }}
data:
  PATH_BACKUP: {{ .Values.minio.pathBackup }}
  PATH_COMPRESS: {{ .Values.minio.pathCompress }}
  DELETE_OLD_BACKUPS: {{ .Values.minio.deleteOldBackups | quote }}
  MAX_BACKUP_DAYS: {{ .Values.minio.maxBackupDays | quote }}
{{- end }}