{{- if .Values.global.serviceSelector.pgsql }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm-{{ .Values.pgsql.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.pgsql.serviceName }}
data:
  BACKUP_DATABASES: {{ .Values.pgsql.backupDatabases | quote }}
  BACKUP_STORAGE: {{ .Values.pgsql.backupStorage | quote }}
  DELETE_OLD_BACKUPS: {{ .Values.pgsql.deleteOldBackups | quote }}
  MAX_BACKUP_DAYS: {{ .Values.pgsql.maxBackupDays | quote }}
{{- end }}