{{- if .Values.global.serviceSelector.redis }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm-{{ .Values.redis.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.redis.serviceName }}
data:
  BACKUP_STORAGE: {{ .Values.redis.backupStorage | quote }}
  WAIT_SAVE_RDB: {{ .Values.redis.waitSaveRdb | quote }}
  DELETE_OLD_BACKUPS: {{ .Values.redis.deleteOldBackups | quote }}
  MAX_BACKUP_DAYS: {{ .Values.redis.maxBackupDays | quote }}
{{- end }}
