{{- if .Values.global.serviceSelector.rsync }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-cm-{{ .Values.rsync.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.rsync.serviceName }}
data:
  BACKUP_STORAGE: {{ .Values.rsync.backupStorage | quote }}
  DELETE_OLD_BACKUPS: {{ .Values.rsync.deleteOldBackups | quote }}
  MAX_BACKUP_DAYS: {{ .Values.rsync.maxBackupDays | quote }}
{{- end }}
