{{- if .Values.createBuildConfig }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.imageStream.name }}
  labels:
    app: {{ include "mi-chart.name" . }}
spec:
  lookupPolicy:
    local: false
{{- end }}
