{{- if .Values.openshift.createBuildConfig }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.imageStream.name }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
spec:
  lookupPolicy:
    local: false
{{- end }}
