{{- if .Values.global.serviceSelector.redis }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.redis.serviceName }}
  labels:
    app: {{ .Values.redis.serviceName }}
stringData:
  DB_PASS: {{ .Values.redis.dbPass | quote }}
{{- end }}
