{{- if .Values.global.serviceSelector.mysql }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.mysql.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.mysql.serviceName }}
stringData:
  DB_PASS: {{ .Values.mysql.dbPass | quote }}
  DB_USER: {{ .Values.mysql.dbUser | quote }}
{{- end }}
