{{- if .Values.global.serviceSelector.mongo }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.mongo.serviceName }}
  labels:
    app: {{ .Values.mongo.serviceName }}
stringData:
  DB_PASS: {{ .Values.mongo.dbPass | quote }}
  DB_USER: {{ .Values.mongo.dbUser | quote }}
{{- end }}
