{{- if and .Values.global.serviceSelector.redis (not .Values.redis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.redis.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.redis.serviceName }}
stringData:
  DB_PASS: {{ .Values.redis.dbPass | quote }}
{{- end }}
