{{- if and .Values.global.serviceSelector.pgsql (not .Values.pgsql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.pgsql.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.pgsql.serviceName }}
stringData:
  DB_HOST: {{ .Values.pgsql.dbHost | quote }}
  DB_PASS: {{ .Values.pgsql.dbPass | quote }}
  DB_USER: {{ .Values.pgsql.dbUser | quote }}
{{- end }}
