{{- if and .Values.global.serviceSelector.minio (not .Values.minio.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.minio.serviceName }}
  labels:
    helm.sh/chart: {{ include "arpovea-tools.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ include "arpovea-tools.releaseName" . }}
    app: {{ .Values.minio.serviceName }}
stringData:
  USERMINIO: {{ .Values.minio.user }}
  PASSWORDMINIO: {{ .Values.minio.password }}
{{- end }}