{{- if .Values.global.serviceSelector.minio }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.minio.serviceName }}
  labels:
    app: {{ .Values.minio.serviceName }}
stringData:
  USERMINIO: {{ .Values.minio.user }}
  PASSWORDMINIO: {{ .Values.minio.password }}
{{- end }}