{{- if .Values.global.serviceSelector.pgsql }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.pgsql.serviceName }}
  labels:
    app: {{ .Values.pgsql.serviceName }}
stringData:
  DB_PASS: {{ .Values.pgsql.dbPass | quote }}
  DB_USER: {{ .Values.pgsql.dbUser | quote }}
{{- end }}
