{{- if .Values.global.serviceSelector.mysql }}
apiVersion: v1
kind: Secret
metadata:
  name: cronjob-secret-{{ .Values.mysql.serviceName }}
  labels:
    app: {{ .Values.mysql.serviceName }}
stringData:
  DB_PASS: {{ .Values.mysql.dbPass | quote }}
  DB_USER: {{ .Values.mysql.dbUser | quote }}
{{- end }}
