name: Build and Push Docker image on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      id: tag_name
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: "{{defaultContext}}:docker"
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.tag }}

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.52.0/trivy_0.52.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.52.0_Linux-64bit.deb

    - name: Scan Docker image with Trivy
      run: |
        trivy image --format json --output trivy_report.json ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.tag }}

    - name: Upload Trivy scan results
      uses: actions/upload-artifact@v4
      with:
        name: vulnerabilidades
        path: trivy_report.json
