name: Test de formato Helm + Push desde develop a main

on:
  workflow_run:
    workflows: ["MySQL Backup Test"]
    types:
      - 

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.4

      - name: Helm Lint
        run: helm lint ./helm-chart

  merge-to-main:
    runs-on: ubuntu-latest
    needs: helm-lint
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITACTIONS}}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Merge develop into main
        run: |
          git fetch origin
          git checkout main
          git merge origin/develop --no-ff -m "Merging changes from develop to main"
          git push origin main

