name: Helm Lint

on:
  push:
    branches:
      - main
      - develop

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.4

      - name: Helm Lint
        run: helm lint ./helm-chart
