name: Test de formato Helm + Push desde develop a main

on:
  push:
    branches:
      - main
      - develop

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.14.4

      - name: Helm Lint
        run: helm lint ./helm-chart

  merge-to-main:
    runs-on: ubuntu-latest
    needs: helm-lint
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Merge develop into main
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git merge --no-ff origin/develop -m "Merging changes from develop to main"
          git push origin main

