name: Package and Push Helm Chart to GitHub Packages

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: '3.14.4'

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract tag name
      id: tag_name
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash

    - name: Package Helm Chart
      run: |
        helm package ./helm-chart --version ${{ env.tag }} --destination ./chart-packages

    - name: Push Helm Chart to GitHub Packages
      run: |
        helm push ./chart-packages/$(ls ./chart-packages/*.tgz) oci://ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
