name: Package and Push Helm Chart to Docker Hub

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: '3.14.4'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      id: tag_name
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      shell: bash

    - name: Package Helm Chart
      run: |
        helm package ./helm-chart --version ${{ env.tag }} --destination ./chart-packages
        ls -la ./chart-packages
        
    - name: Push Helm Chart to Docker Hub
      run: |
        helm registry login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
        helm push ./chart-packages/$(basename ./helm-chart)-${{ env.tag }}.tgz oci://docker.io/${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY_HELM }}:${{ env.tag }}