name: MongoDB Backup Test

on:
  workflow_run:
    workflows: ["PostgreSQL Backup Test"]
    types:
      - completed

jobs:
  test-dump-mongodb:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    services:
      mongodb:
        image: mongo:7.0
        env:
          MONGO_INITDB_ROOT_USERNAME: dummyuser
          MONGO_INITDB_ROOT_PASSWORD: dummypass
          MONGO_INITDB_DATABASE:  dummymongo
        ports:
          - 27017:27017
          
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check MongoDB Availability
      run: |
        until mongosh --username dummyuser --password dummypass --eval "db.adminCommand('ping')" > /dev/null; do
          echo "Waiting for MongoDB to become ready..."
          sleep 2
        done
        echo "MongoDB is ready."

    - name: Run Backup Script
      env:
        DB_USER: dummyuser
        DB_PASS: dummypass
        DB_HOST: 127.0.1.1
        ALL_DATABASES: "true"
        BACKUP_STORAGE: "/tmp/mongodump"
      run: |
        mkdir -p $BACKUP_STORAGE
        chmod +x ./docker/scripts/entrypoint_mongo_dump.sh
        ./docker/scripts/entrypoint_mongo_dump.sh
