name: MySQL Backup Test

on:
  push:
    branches:
      - develop

jobs:
  test-dump-mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: dummypass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -pdummypass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -pdummypass --silent; do
          sleep 1
        done

    - name: Run Backup Script
      env:
        DB_USER: root
        DB_PASS: dummypass
        DB_HOST: 127.0.0.1
        ALL_DATABASES: "true"
        BACKUP_STORAGE: "/tmp/mysqldump"
      run: |
        mkdir -p $BACKUP_STORAGE
        chmod +x ./docker/scripts/entrypoint_mysql_dump.sh
        ./docker/scripts/entrypoint_mysql_dump.sh

    - name: Check Results
      run: ls -lah $BACKUP_STORAGE
