name: PostgreSQL Backup Test

on:
  workflow_run:
    workflows: ["MySQL Backup Test"]
    types:
      - completed

jobs:
  test-dump-postgresql:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.head_branch == 'develop' }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: dummyuser
          POSTGRES_PASSWORD: dummypass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U dummyuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h localhost -p 5432 -U dummyuser; do
          echo "Waiting for PostgreSQL to become ready..."
          sleep 2
        done
        echo "PostgreSQL is ready."

    - name: Run Backup Script
      env:
        DB_USER: dummyuser
        DB_PASS: dummypass
        DB_HOST: localhost
        DB_DATABASE: mydatabase
        ALL_DATABASES: "true"
        BACKUP_STORAGE: "/tmp/pgdump"
      run: |
        mkdir -p $BACKUP_STORAGE
        chmod +x ./docker/scripts/entrypoint_postgresql_dump.sh
        ./docker/scripts/entrypoint_postgresql_dump.sh

    - name: Check Results
      run: |
        ls -lah $BACKUP_STORAGE
        cat $BACKUP_STORAGE/checksums.txt

    - name: Cleanup
      if: always()
      run: |
        echo "Cleaning up..."
        rm -rf $BACKUP_STORAGE
